name: ubuntu-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: |
          sudo apt update
          sudo apt-get install -y mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - name: configure
        env:
          CC: gcc-9
          CXX: g++-9
        run: |
          cd examples
          mkdir build
          cd build
          cmake .. -G"Unix Makefiles" -Dcinolib_DIR="/home/runner/work/cinolib/cinolib"
          pwd
      - name: build
        run: |
          cd examples
          cd build
          pwd
          cmake --build . --parallel 8
